---
source: crates/tlang_test_runner/src/main.rs
description: Known failure - output may not match expected
expression: output
input_file: tests/known_failures/advanced_function_composition.tlang
---
=== Advanced Function Composition Test ===
6
120
15
30
125
192
0
1
1
1
2
fn factorial_helper#290(num, acc)
fn factorial_helper#290(num, acc)


thread 'main' panicked at crates/tlang_runtime/tlang_memory/src/state.rs:328:9:
Function `"anonymous"` expects 1 arguments, but got 0
  at root 141:1

stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: tlang_memory::state::InterpreterState::panic
   3: tlang_interpreter::Interpreter::eval_fn_call
   4: tlang_interpreter::Interpreter::eval_call_object
   5: tlang_interpreter::Interpreter::eval_call
   6: tlang_interpreter::Interpreter::eval_call
   7: tlang_interpreter::Interpreter::eval_stmts
   8: tlangdi::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
